In [1]:
import os
from dotenv import load_dotenv

# Explicitly providing path to '.env'
from pathlib import Path  # Python 3.6+ only
# Load .env variables
_ = load_dotenv(dotenv_path=f"{Path().resolve().parents[0]}/.env")

# with the new api
from importnb import imports
with imports("ipynb"):
    from utils import to_timestamp, df_data_sensors, df_to_csv, df_from_csv, to_file_name

In [2]:
# Start Date Time ISO 8601 Format, TZ='America/Bogota' -05:00
START_ISO8601_DATETIME = os.getenv("START_ISO8601_DATETIME", None)
# End Date Time ISO 8601 Format, TZ='America/Bogota' -05:00
END_ISO8601_DATETIME = os.getenv("END_ISO8601_DATETIME", None)

## Tangaras

In [3]:
file_name = to_file_name("tangaras", START_ISO8601_DATETIME, END_ISO8601_DATETIME)
file_name

2024-09-20 18:21:35.249 | DEBUG    | utils:to_file_name:448 - Run to_file_name:

2024-09-20 18:21:35.249 | DEBUG    | utils:to_file_name:449 - File Name: tangaras_2024-08-01_00-00-00_UTC-0500_2024-08-31_23-59-59_UTC-0500.csv

'tangaras_2024-08-01_00-00-00_UTC-0500_2024-08-31_23-59-59_UTC-0500.csv'

In [4]:
# Tangaras from CSV
df_tangaras = df_from_csv(file_name, dtindex=False)
print(f"Total Tangara Sensors: {len(df_tangaras)}")

df_tangaras

2024-09-20 18:21:35.269 | DEBUG    | utils:df_from_csv:263 - Run df_from_csv:

2024-09-20 18:21:35.269 | DEBUG    | utils:df_from_csv:264 - Load DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-mlds-unal-2024/src/tangara/data/0_raw/tangaras_2024-08-01_00-00-00_UTC-0500_2024-08-31_23-59-59_UTC-0500.csv

Total Tangara Sensors: 38

,ID,GEOHASH,MAC,GEOLOCATION,LATITUDE,LONGITUDE
0,TANGARA_B7BE,d29e6de,D29ESP32DE0B7BE,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
1,TANGARA_C752,d29e6de,D29ESP32DE0C752,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
2,TANGARA_A682,d29e6de,D29ESP32DE3A682,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
3,TANGARA_ADD6,d29e6de,D29ESP32DE3ADD6,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
4,TANGARA_B9CA,d29e6de,D29ESP32DE3B9CA,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
5,TANGARA_BC5A,d29e6de,D29ESP32DE3BC5A,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
6,TANGARA_BCC6,d29e6de,D29ESP32DE3BCC6,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
7,TANGARA_BD5E,d29e6de,D29ESP32DE3BD5E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
8,TANGARA_BE12,d29e6de,D29ESP32DE3BE12,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
9,TANGARA_2BDE,d29efb4,D29ESP32DE52BDE,3.4723663330078125 -76.51634216308594,3.472366,-76.516342
10,TANGARA_3B7E,d29ee40,D29ESP32DE53B7E,3.4394073486328125 -76.50810241699219,3.439407,-76.508102
11,TANGARA_421A,d29egkt,D29ESP32DE5421A,3.4970855712890625 -76.49024963378906,3.497086,-76.490250
12,TANGARA_79CA,d29e6de,D29ESP32DE679CA,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
13,TANGARA_1402,d29e6de,D29ESP32DE71402,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
14,TANGARA_157E,d29e6de,D29ESP32DE7157E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
15,TANGARA_1DE2,d29e6de,D29ESP32DE71DE2,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
16,TANGARA_298A,d29e6de,D29ESP32DE7298A,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
17,TANGARA_3376,d29e6de,D29ESP32DE73376,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
18,TANGARA_5636,d29e7tv,D29ESP32DE85636,3.4160614013671875 -76.47926330566406,3.416061,-76.479263
19,TANGARA_D282,d29e6fj,D29ESP32DE8D282,3.3954620361328125 -76.51222229003906,3.395462,-76.512222
20,TANGARA_4B1A,d29esj8,D29ESP32DE94B1A,3.4586334228515625 -76.46415710449219,3.458633,-76.464157
21,TANGARA_1106,d29edzu,D29ESP32DEC1106,3.4709930419921875 -76.51359558105469,3.470993,-76.513596
22,TANGARA_1282,d29edvt,D29ESP32DED1282,3.4586334228515625 -76.51222229003906,3.458633,-76.512222
23,TANGARA_14D6,d29eg4k,D29ESP32DED14D6,3.4847259521484375 -76.50260925292969,3.484726,-76.502609
24,TANGARA_1A1E,d29e7qm,D29ESP32DED1A1E,3.4188079833984375 -76.49024963378906,3.418808,-76.490250
25,TANGARA_2492,d29e4y4,D29ESP32DED2492,3.3734893798828125 -76.51634216308594,3.373489,-76.516342
26,TANGARA_2E9A,d29ed62,D29ESP32DED2E9A,3.4407806396484375 -76.54106140136719,3.440781,-76.541061
27,TANGARA_2FF6,d29e66v,D29ESP32DED2FF6,3.3995819091796875 -76.53419494628906,3.399582,-76.534195
28,TANGARA_307A,d29e48s,D29ESP32DED307A,3.3432769775390625 -76.52458190917969,3.343277,-76.524582
29,TANGARA_3782,d29eddn,D29ESP32DED3782,3.4394073486328125 -76.52183532714844,3.439407,-76.521835
30,TANGARA_F212,d29ed9s,D29ESP32DEDF212,3.4366607666015625 -76.52458190917969,3.436661,-76.524582
31,TANGARA_1712,d29dfx4,D29ESP32DEE1712,3.3350372314453125 -76.52732849121094,3.335037,-76.527328
32,TANGARA_A43A,d29e6de,D29ESP32DEFA43A,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
33,TANGARA_C17E,d29e6de,D29ESP32DEFC17E,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
34,TANGARA_CA62,d29e6de,D29ESP32DEFCA62,3.3982086181640625 -76.52595520019531,3.398209,-76.525955
35,TANGARA_532E,d29ed74,D29TTGOT7D532E,3.4449005126953125 -76.53831481933594,3.444901,-76.538315
36,TANGARA_F1AE,d29eg69,D29TTGOTD8F1AE,3.4860992431640625 -76.49574279785156,3.486099,-76.495743
37,TANGARA_06BE,d29e6de,D29TTGOTD906BE,3.3982086181640625 -76.52595520019531,3.398209,-76.525955

## Humidity Raw Data

In [5]:
# Start Date Time ISO 8601 Format, TZ='America/Bogota' -05:00
START_ISO8601_DATETIME = os.getenv("START_ISO8601_DATETIME", None)
start_timestamp = to_timestamp(START_ISO8601_DATETIME)
# End Date Time ISO 8601 Format, TZ='America/Bogota' -05:00
END_ISO8601_DATETIME = os.getenv("END_ISO8601_DATETIME", None)
end_timestamp = to_timestamp(os.getenv("END_ISO8601_DATETIME", None))

# GROUP BY TIME
GROUP_BY_TIME = os.getenv("GROUP_BY_TIME", None)

print(f'Since: {START_ISO8601_DATETIME} -> {start_timestamp}, Until: {END_ISO8601_DATETIME} -> {end_timestamp}')
print(f"Group by Time: {GROUP_BY_TIME}")

2024-09-20 18:21:35.279 | DEBUG    | utils:to_timestamp:79 - Run to_timestamp:

2024-09-20 18:21:35.279 | DEBUG    | utils:to_timestamp:80 - datetime_iso8601: 2024-08-01T00:00:00-05:00, Timestamp: 1722488400000

2024-09-20 18:21:35.280 | DEBUG    | utils:to_timestamp:79 - Run to_timestamp:

2024-09-20 18:21:35.281 | DEBUG    | utils:to_timestamp:80 - datetime_iso8601: 2024-08-31T23:59:59-05:00, Timestamp: 1725166799000

Since: 2024-08-01T00:00:00-05:00 -> 1722488400000, Until: 2024-08-31T23:59:59-05:00 -> 1725166799000
Group by Time: 30s

In [6]:
# Humidity Data Frame Sensors
df_hum_raw = df_data_sensors(df_tangaras, start_timestamp, end_timestamp, 'hum', GROUP_BY_TIME)
df_hum_raw.shape

2024-09-20 18:21:35.285 | DEBUG    | utils:query_measure:193 - Run query_measure:

2024-09-20 18:21:35.286 | DEBUG    | utils:query_measure:194 - sql_query: SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE0B7BE') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE0C752') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3A682') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3ADD6') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3B9CA') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3BC5A') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3BCC6') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3BD5E') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE3BE12') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE52BDE') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE53B7E') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE5421A') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE679CA') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE71402') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE7157E') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE71DE2') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE7298A') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE73376') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE85636') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE8D282') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DE94B1A') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DEC1106') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DED1282') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DED14D6') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DED1A1E') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DED2492') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DED2E9A') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DED2FF6') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DED307A') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DED3782') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DEDF212') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DEE1712') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DEFA43A') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DEFC17E') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29ESP32DEFCA62') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29TTGOT7D532E') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29TTGOTD8F1AE') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null); SELECT last("hum") FROM "fixed_stations_01" WHERE ("name" = 'D29TTGOTD906BE') AND time >= 1722488400000ms AND time <= 1725166799000ms GROUP BY time(30s) fill(null)

2024-09-20 18:22:14.556 | DEBUG    | utils:request_influxdb:118 - Run request_influxdb:

2024-09-20 18:22:14.557 | DEBUG    | utils:request_influxdb:119 - response: <Response [200]>

/home/sebaxtian/Workspaces/Tangara/tangara-mlds-unal-2024/src/tangara/notebooks/utils.ipynb:411: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  df_sensors = df_sensors.asfreq(freq=group_by_time)
2024-09-20 18:22:16.349 | DEBUG    | utils:df_data_sensors:419 - Run df_data_sensors:

2024-09-20 18:22:16.350 | DEBUG    | utils:df_data_sensors:420 - Measure Data Frame Sensors: <class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 89280 entries, 2024-08-01 00:00:00-05:00 to 2024-08-31 23:59:30-05:00
Freq: 30s
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TANGARA_B7BE  67718 non-null  float64
 1   TANGARA_C752  48966 non-null  float64
 2   TANGARA_A682  85089 non-null  float64
 3   TANGARA_ADD6  64851 non-null  float64
 4   TANGARA_B9CA  72173 non-null  float64
 5   TANGARA_BC5A  88271 non-null  float64
 6   TANGARA_BCC6  72479 non-null  float64
 7   TANGARA_BD5E  48948 non-null  float64
 8   TANGARA_BE12  48922 non-null  float64
 9   TANGARA_2BDE  85978 non-null  float64
 10  TANGARA_3B7E  47921 non-null  float64
 11  TANGARA_421A  34281 non-null  float64
 12  TANGARA_79CA  62526 non-null  float64
 13  TANGARA_1402  72524 non-null  float64
 14  TANGARA_157E  65778 non-null  float64
 15  TANGARA_1DE2  72288 non-null  float64
 16  TANGARA_298A  88393 non-null  float64
 17  TANGARA_3376  88215 non-null  float64
 18  TANGARA_5636  67862 non-null  float64
 19  TANGARA_D282  39338 non-null  float64
 20  TANGARA_4B1A  18174 non-null  float64
 21  TANGARA_1106  87592 non-null  float64
 22  TANGARA_1282  54523 non-null  float64
 23  TANGARA_14D6  85874 non-null  float64
 24  TANGARA_1A1E  87122 non-null  float64
 25  TANGARA_2492  69703 non-null  float64
dtypes: float64(26)
memory usage: 18.4 MB

(89280, 26)

In [7]:
df_hum_raw

,TANGARA_B7BE,TANGARA_C752,TANGARA_A682,TANGARA_ADD6,TANGARA_B9CA,TANGARA_BC5A,TANGARA_BCC6,TANGARA_BD5E,TANGARA_BE12,TANGARA_2BDE,...,TANGARA_298A,TANGARA_3376,TANGARA_5636,TANGARA_D282,TANGARA_4B1A,TANGARA_1106,TANGARA_1282,TANGARA_14D6,TANGARA_1A1E,TANGARA_2492
DATETIME,,,,,,,,,,,,,,,,,,,,,
2024-08-01 00:00:00-05:00,43.16,NaN,41.37,39.94,37.09,40.15,36.50,NaN,NaN,NaN,...,36.43,41.84,NaN,NaN,68.74,NaN,NaN,NaN,74.53,NaN
2024-08-01 00:00:30-05:00,43.30,NaN,41.49,39.94,37.06,40.15,36.60,NaN,NaN,56.23,...,36.48,41.83,61.54,49.47,68.73,54.42,63.35,62.16,74.54,46.48
2024-08-01 00:01:00-05:00,43.16,NaN,41.42,39.92,37.09,40.17,36.67,NaN,NaN,56.27,...,36.52,41.87,61.56,49.62,68.75,54.56,63.40,62.39,74.58,46.43
2024-08-01 00:01:30-05:00,42.99,NaN,41.40,39.92,37.05,40.17,36.60,NaN,NaN,56.43,...,36.53,41.79,61.68,49.86,68.77,54.51,63.38,62.46,74.56,46.59
2024-08-01 00:02:00-05:00,42.99,NaN,41.38,39.97,37.08,40.16,36.48,NaN,NaN,56.46,...,36.52,41.84,61.92,50.11,68.81,54.69,63.14,62.63,74.62,46.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-31 23:57:30-05:00,NaN,41.59,NaN,51.09,36.30,45.57,44.68,44.44,45.91,57.53,...,44.32,46.88,63.91,NaN,NaN,54.82,NaN,61.38,72.94,52.46
2024-08-31 23:58:00-05:00,NaN,41.63,NaN,51.11,36.30,45.61,44.81,44.45,45.95,57.55,...,44.35,46.89,63.96,NaN,NaN,54.89,NaN,61.38,73.23,52.47
2024-08-31 23:58:30-05:00,NaN,41.63,NaN,51.07,36.27,45.63,44.81,44.45,45.88,57.67,...,44.32,46.87,63.85,NaN,NaN,54.91,NaN,61.38,73.60,52.32
2024-08-31 23:59:00-05:00,NaN,41.66,NaN,51.10,36.30,45.66,45.05,44.45,45.96,NaN,...,44.51,46.87,NaN,NaN,NaN,NaN,NaN,NaN,73.34,NaN
2024-08-31 23:59:30-05:00,NaN,41.69,NaN,51.10,36.27,45.76,44.81,44.44,46.03,NaN,...,44.46,46.92,NaN,NaN,NaN,NaN,NaN,NaN,73.75,NaN

In [8]:
file_name = to_file_name("hum_raw", START_ISO8601_DATETIME, END_ISO8601_DATETIME)
file_name

2024-09-20 18:22:16.381 | DEBUG    | utils:to_file_name:448 - Run to_file_name:

2024-09-20 18:22:16.382 | DEBUG    | utils:to_file_name:449 - File Name: hum_raw_2024-08-01_00-00-00_UTC-0500_2024-08-31_23-59-59_UTC-0500.csv

'hum_raw_2024-08-01_00-00-00_UTC-0500_2024-08-31_23-59-59_UTC-0500.csv'

In [9]:
# Save Humidity Data Frame Sensors into CSV file
df_to_csv(df_hum_raw, file_name)

2024-09-20 18:22:17.260 | DEBUG    | utils:df_to_csv:228 - Run df_to_csv:

2024-09-20 18:22:17.260 | DEBUG    | utils:df_to_csv:229 - Save DataFrame: /home/sebaxtian/Workspaces/Tangara/tangara-mlds-unal-2024/src/tangara/data/0_raw/hum_raw_2024-08-01_00-00-00_UTC-0500_2024-08-31_23-59-59_UTC-0500.csv

In [10]:
df_hum_raw.shape

(89280, 26)